const express = require("express");
const { Configuration, OpenAIApi } = require("openai");
require("dotenv").config();

const app = express();
app.use(express.json());

const configuration = new Configuration({
  apiKey: process.env.API_KEY,
});

const openai = new OpenAIApi(configuration);


app.post("/generate-response", async (req, res) => {
  try {
    const { technology = "AI", experience = "1" } = req.body;

    console.log(technology);
    console.log(experience);
    
    const System = `You are a software developer with 5 years of experience in ${technology}. You are taking interview of a candidate who is applying for a ${technology} developer position having ${experience} year of experience. Now you have to generate a set of ten questions based on ${technology} knowledge in Json format. Here's the example of how the questions will be generated by you will look like enclosed in tipple quotes. Give me response in the minified Json format such as these examples.
    
    '''
    [{"id":0,"question":"What is react?"},{"id":1,"question":"What is virtual DOM in react?"},{"id":2,"question":"What is the difference of virtual DOM and actual DOM?"}]
    '''`;



    const completion = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: [
        { role: "system", content: System },
        // { role: "user", content: prompt },
      ],
    });

    const answer = completion.data.choices[0].message.content.trim();
    // res.json(answer);
    res.send({questionList: JSON.parse(answer), usage: completion.data.usage});
  } catch (error) {
    console.error("Error:", error.message);
    res.status(500).json({ error: error });
  }
});

app.post("/analyze", async(req, res)=>{
  try {
    const { technology = "AI", experience = "1" } = req.body;

    console.log(technology);
    console.log(experience);
    
    const System = `You are a software developer with 5 years of experience in react. You are taking interview of a candidate who is applying for a react developer position having 1 year of experience. Now you have to generate an overall rating of the entire interview and how did the candidate performed in terms of deep knowledge in react. Here's the entire conversation in a Json format. In the Json you can find the question asked to the candidate and his answer in natural language. After analysing the entire conversation, you will create a Json object as the analysis result. There's also an example of the analysis Json. Give me response in the Json format such as these examples.
    
    This is the entire conversation.
        '''
    [
        {
            "question": "What is react?",
            "answer": "React was a PHP based language."
        },
        {
            "question": "What is virtual DOM in react?",
            "answer": "Virtual DOM been has a node list which react play to determine the update in UI"
        },
        {
            "question": "What is the difference of virtual DOM and actual DOM?",
            "answer": "null"
        }
    ]
        '''
    Now by taking and analyzing the above JSON array add two keys like communication_skill_of_the_candidate and correctness_of_the_answer with accurate percentage value and then give me the new JSON array excluding the question and answer key for each question.
    
        `;



    const completion = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      temperature: 0,
      messages: [
        { role: "system", content: System },
        // { role: "user", content: prompt },
      ],
    });

    const answer = completion.data.choices[0].message.content.trim();
    // res.json(answer);
    res.send(answer);
  } catch (error) {
    console.error("Error:", error.message);
    res.status(500).json({ error: error });
  }
})

const port = 3000;
app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});
